version: "3.9"

services:
  # CMS back-end server
  cms_back:
    build: ./cms_back
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_STRING: ${DB_STRING}
      DB_STRING_PROD: ${DB_STRING_PROD}
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    restart: unless-stopped

  # CMS front-end server
  cms_front:
    build: ./cms_front
    restart: unless-stopped

  # webserver nginx
  webserver:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - cms_back
      - cms_front

  # certbot for ssl
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email zakeri.arshia@yahoo.com -d vima-test.site  -d www.vima-test.site -d cms.vima-test.site --agree-tos
