version: "3.9"

services:
  # CMS back-end server
  cms_back:
    build: ./cms_back
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_STRING: ${DB_STRING}
      DB_STRING_PROD: ${DB_STRING_PROD}
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    restart: unless-stopped
    networks:
      - caddy-net

  # CMS front-end server
  cms_front:
    build: ./cms_front
    restart: unless-stopped
    networks:
      - caddy-net
  #Caddy as a webserver
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy-net
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
networks:
  caddy-net:
